/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketconcert;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author LENOVO
 */
public class RegisterForm extends javax.swing.JFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    
    Koneksi k = new Koneksi();
    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        k.connect();
        
        loginLink.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        regBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    
    class Users extends RegisterForm {
        String fullname, nickname, phoneNumbers, password;
        
        public Users() {
            fullname = nameField.getText();
            nickname = nicknameField.getText();
            phoneNumbers = numbersField.getText();
            password = passwField.getText();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        regLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nicknameLabel = new javax.swing.JLabel();
        nicknameField = new javax.swing.JTextField();
        numbersLabel = new javax.swing.JLabel();
        regBtn = new javax.swing.JButton();
        loginLink = new javax.swing.JLabel();
        appLogo = new javax.swing.JLabel();
        numbersField = new javax.swing.JTextField();
        passwLabel = new javax.swing.JLabel();
        passwField = new javax.swing.JPasswordField();
        repeatPasswLabel = new javax.swing.JLabel();
        repeatPasswField = new javax.swing.JPasswordField();
        emailLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        regLabel.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        regLabel.setForeground(new java.awt.Color(0, 102, 153));
        regLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regLabel.setText("REGISTER");

        nameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 102, 153));
        nameLabel.setText("Full name:");

        nicknameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(0, 102, 153));
        nicknameLabel.setText("Nickname:");

        nicknameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nicknameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameFieldActionPerformed(evt);
            }
        });

        numbersLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        numbersLabel.setForeground(new java.awt.Color(0, 102, 153));
        numbersLabel.setText("Phone numbers:");

        regBtn.setBackground(new java.awt.Color(0, 102, 153));
        regBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        regBtn.setForeground(new java.awt.Color(255, 255, 255));
        regBtn.setText("Register");
        regBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regBtnMouseExited(evt);
            }
        });
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        loginLink.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginLink.setForeground(new java.awt.Color(0, 102, 153));
        loginLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLink.setText("Already have an account?");
        loginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLinkMouseExited(evt);
            }
        });

        appLogo.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        appLogo.setForeground(new java.awt.Color(0, 102, 153));
        appLogo.setText(" Ticket Concert App");

        numbersField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numbersField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersFieldActionPerformed(evt);
            }
        });

        passwLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwLabel.setForeground(new java.awt.Color(0, 102, 153));
        passwLabel.setText("Password:");

        repeatPasswLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        repeatPasswLabel.setForeground(new java.awt.Color(0, 102, 153));
        repeatPasswLabel.setText("Repeat password:");

        emailLabel1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(0, 102, 153));
        emailLabel1.setText("*Note: the phone numbers must be same with yout WA numbers.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(appLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameField)
                                    .addComponent(nicknameField)
                                    .addComponent(numbersField)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numbersLabel)
                                            .addComponent(nameLabel)
                                            .addComponent(nicknameLabel))
                                        .addGap(216, 216, 216)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwField)
                                    .addComponent(repeatPasswField)
                                    .addComponent(regBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loginLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(repeatPasswLabel)
                                            .addComponent(passwLabel)
                                            .addComponent(emailLabel1))
                                        .addGap(35, 35, 35)))))))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appLogo)
                .addGap(47, 47, 47)
                .addComponent(regLabel)
                .addGap(40, 40, 40)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nicknameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numbersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numbersField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel1)
                .addGap(18, 18, 18)
                .addComponent(passwLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(repeatPasswLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repeatPasswField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginLink)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nicknameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameFieldActionPerformed

    private void numbersFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbersFieldActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        // TODO add your handling code here:
        if(nameField.getText().equals("") || 
           nicknameField.getText().equals("") ||
           numbersField.getText().equals("") || 
           passwField.getText().equals("") ||
           repeatPasswField.getText().equals("")) {
            JOptionPane.showMessageDialog( null, "There's still empty field.");
        } else if(!repeatPasswField.getText().equals(passwField.getText())) {
            JOptionPane.showMessageDialog(null, "The password doesn't match each other.");
        } else if(nameField.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Wrong fullname format.");
        } else if(nicknameField.getText().contains(" ") ||
                  nicknameField.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Wrong nickname format.");
        } else if(numbersField.getText().matches("[a-zA-Z]+") ||
                  numbersField.getText().length() != 12) {
            JOptionPane.showMessageDialog(null, "Wrong phone numbers format.");
        } else {
            Users usr = new Users();
            
            try {
                this.stat = k.getCon().prepareStatement("INSERT INTO users "
                        + "(fullname, nickname, phone_numbers, password) "
                        + "VALUES(?,?,?,?)");
                stat.setString(1, usr.fullname);
                stat.setString(2, usr.nickname);
                stat.setString(3, usr.phoneNumbers);
                stat.setString(4, usr.password);
                stat.executeUpdate();
                
                this.stat = k.getCon().prepareStatement("INSERT INTO wallet "
                        + "(numbers_phone, balance) VALUES(?,?)");
                stat.setString(1, usr.phoneNumbers);
                stat.setInt(2, 0);
                stat.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Please back to login.");
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_regBtnActionPerformed

    private void loginLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_loginLinkMouseClicked

    private void loginLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseEntered
        // TODO add your handling code here:
        loginLink.setForeground(new Color(105, 105, 105));
    }//GEN-LAST:event_loginLinkMouseEntered

    private void loginLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseExited
        // TODO add your handling code here:
        loginLink.setForeground(new Color(0,102,153));
    }//GEN-LAST:event_loginLinkMouseExited

    private void regBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regBtnMouseExited
        // TODO add your handling code here:
        regBtn.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_regBtnMouseExited

    private void regBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regBtnMouseEntered
        // TODO add your handling code here:
        regBtn.setBackground(new Color(0, 76, 114));
    }//GEN-LAST:event_regBtnMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLogo;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginLink;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nicknameField;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JTextField numbersField;
    private javax.swing.JLabel numbersLabel;
    private javax.swing.JPasswordField passwField;
    private javax.swing.JLabel passwLabel;
    private javax.swing.JButton regBtn;
    private javax.swing.JLabel regLabel;
    private javax.swing.JPasswordField repeatPasswField;
    private javax.swing.JLabel repeatPasswLabel;
    // End of variables declaration//GEN-END:variables
}
